import StyledComponentsRegistry from '../../lib/registry'
import { Poppins } from 'next/font/google'
import GlobalStyle from '@/styles/Globals'

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: 'FrontEndMentor Challenges by Suami Rocha',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <StyledComponentsRegistry>
        <GlobalStyle/>
        {children}
      </StyledComponentsRegistry>
      </body>
    </html>
  )
}
